/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIFrames;

import DBConnection.ConnectDB;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronaldo
 */
public class Login_Window extends javax.swing.JFrame {

    /**
     * Creates new form Logiin_Window
     */
    public Login_Window() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit_Button = new javax.swing.JButton();
        DecorationPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Username_TextField = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        Password_TextField = new javax.swing.JPasswordField();
        LoginButton_Panel1 = new javax.swing.JPanel();
        Login_Button1 = new javax.swing.JButton();
        LoginButton_Panel = new javax.swing.JPanel();
        Login_Button = new javax.swing.JButton();
        jLabelLogIntext = new javax.swing.JLabel();
        Jlabeltext1prices = new javax.swing.JLabel();
        jLabelgoldpink = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit Button.png"))); // NOI18N
        Exit_Button.setToolTipText("");
        Exit_Button.setBorder(null);
        Exit_Button.setContentAreaFilled(false);
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 50, 50));

        DecorationPanel.setBackground(new java.awt.Color(0, 0, 0));
        DecorationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(154, 144, 95));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Username_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Username_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Username_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Username_TextField.setBorder(null);
        Username_TextField.setCaretColor(new java.awt.Color(0, 102, 204));
        Username_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Username_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Username_TextFieldMouseExited(evt);
            }
        });
        Username_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_TextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(Username_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 370, 40));

        jLabelUsername.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Username or Email:");
        jPanel1.add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 230, 30));

        jLabelPassword.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password:");
        jPanel1.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 120, 30));

        Password_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Password_TextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Password_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Password_TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password_TextField.setBorder(null);
        Password_TextField.setCaretColor(new java.awt.Color(0, 102, 204));
        jPanel1.add(Password_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 370, 40));

        LoginButton_Panel1.setBackground(new java.awt.Color(92, 79, 46));
        LoginButton_Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_Button1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Login_Button1.setForeground(new java.awt.Color(255, 255, 255));
        Login_Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Eye Icon.png"))); // NOI18N
        Login_Button1.setBorderPainted(false);
        Login_Button1.setContentAreaFilled(false);
        Login_Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Login_Button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Login_Button1MouseExited(evt);
            }
        });
        Login_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_Button1ActionPerformed(evt);
            }
        });
        LoginButton_Panel1.add(Login_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel1.add(LoginButton_Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 40, -1));

        LoginButton_Panel.setBackground(new java.awt.Color(92, 79, 46));
        LoginButton_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_Button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Login_Button.setForeground(new java.awt.Color(255, 255, 255));
        Login_Button.setText("Login");
        Login_Button.setBorderPainted(false);
        Login_Button.setContentAreaFilled(false);
        Login_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Login_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Login_ButtonMouseExited(evt);
            }
        });
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });
        LoginButton_Panel.add(Login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 30));

        jPanel1.add(LoginButton_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 230, -1));

        DecorationPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 520, 370));

        jLabelLogIntext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login_text(1).png"))); // NOI18N
        DecorationPanel.add(jLabelLogIntext, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 520, 110));

        getContentPane().add(DecorationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 620, 720));

        Jlabeltext1prices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/text_1.png"))); // NOI18N
        Jlabeltext1prices.setText("jLabel2");
        getContentPane().add(Jlabeltext1prices, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 500, 60));

        jLabelgoldpink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gold2.jpg"))); // NOI18N
        getContentPane().add(jLabelgoldpink, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 710, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_TextFieldActionPerformed
       Username_TextField.setText("");
    }//GEN-LAST:event_Username_TextFieldActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
       
       Split_Second.Split_Second.username = Username_TextField.getText();
        
       
       String pUsername = Username_TextField.getText();
       String pPassword = Password_TextField.getText(); 
       
       
        try {
            int identification = ConnectDB.getPersonIdentification(pUsername);
            Split_Second.Split_Second.identification = identification;
            System.out.println(identification);
        
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Login_Window.class.getName()).log(Level.SEVERE, null, ex);
        }
       
      
       
       int res = 0;
       
        try {
            res = DBConnection.ConnectDB.getPersonIdTypePerson(Split_Second.Split_Second.identification);
            
        } catch (SQLException ex) {
            Logger.getLogger(Login_Window.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (res == 0){ //Si es Admin
             Admin_Main_Menu result = new Admin_Main_Menu();
             result.setVisible(true); 
             this.setVisible(false);
             
        }
        else if (res == 1){ // Si es User
             User_Main_Menu result = new User_Main_Menu();
             result.setVisible(true); 
             this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid Username or Password!", "Error", JOptionPane.ERROR_MESSAGE);
           
        }
       
        
          
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void Username_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username_TextFieldMouseEntered
        Username_TextField.setBackground(new java.awt.Color(216,216,216));
    }//GEN-LAST:event_Username_TextFieldMouseEntered

    private void Username_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username_TextFieldMouseExited
         Username_TextField.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Username_TextFieldMouseExited

    private void Login_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_ButtonMouseEntered
        LoginButton_Panel.setBackground(new java.awt.Color(68,58,34));
    }//GEN-LAST:event_Login_ButtonMouseEntered

    private void Login_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_ButtonMouseExited
        LoginButton_Panel.setBackground(new java.awt.Color(92,79,46));
    }//GEN-LAST:event_Login_ButtonMouseExited

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void Login_Button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_Button1MouseEntered
        Password_TextField.setEchoChar((char)0);
    }//GEN-LAST:event_Login_Button1MouseEntered

    private void Login_Button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_Button1MouseExited
        Password_TextField.setEchoChar('*');
    }//GEN-LAST:event_Login_Button1MouseExited

    private void Login_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_Button1ActionPerformed

    /**
     * @param args the command line arguments
    */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DecorationPanel;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JLabel Jlabeltext1prices;
    private javax.swing.JPanel LoginButton_Panel;
    private javax.swing.JPanel LoginButton_Panel1;
    private javax.swing.JButton Login_Button;
    private javax.swing.JButton Login_Button1;
    private javax.swing.JPasswordField Password_TextField;
    private javax.swing.JTextField Username_TextField;
    private javax.swing.JLabel jLabelLogIntext;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelgoldpink;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
