/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIFrames;

import java.awt.Color;
import java.io.File;
import java.sql.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import DBConnection.ConnectDB;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Ronaldo
 */
public class Register_Window extends javax.swing.JFrame {

    /**
     * Creates new form Logiin_Window
     */
    public Register_Window() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit_Button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Clock = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        DecorationPanel = new javax.swing.JPanel();
        LastName_TextField = new javax.swing.JTextField();
        Day_TextFied = new javax.swing.JTextField();
        Password_TextField = new javax.swing.JTextField();
        NewUser_Label = new javax.swing.JLabel();
        RegisterButton_Panel = new javax.swing.JPanel();
        Register_Button = new javax.swing.JButton();
        Identification_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Email_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FirstName_TextField = new javax.swing.JTextField();
        Gender_combobox = new javax.swing.JComboBox<>();
        Photo_Button = new javax.swing.JButton();
        Password_Label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Identification_Label = new javax.swing.JLabel();
        First_Name_Label1 = new javax.swing.JLabel();
        Last_Name_Label1 = new javax.swing.JLabel();
        Email_Label = new javax.swing.JLabel();
        Password_Label1 = new javax.swing.JLabel();
        Username_TextField1 = new javax.swing.JTextField();
        Year_TextField = new javax.swing.JTextField();
        Month_TextField = new javax.swing.JTextField();
        NewUser_Label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit Button.png"))); // NOI18N
        Exit_Button.setToolTipText("");
        Exit_Button.setBorder(null);
        Exit_Button.setContentAreaFilled(false);
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registernow_text.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 500, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/text_2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 530, -1));

        Clock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PinkGold.jpg"))); // NOI18N
        getContentPane().add(Clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 650, 720));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DecorationPanel.setBackground(new java.awt.Color(154, 144, 95));
        DecorationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LastName_TextField.setBackground(new java.awt.Color(255, 255, 255));
        LastName_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LastName_TextField.setForeground(new java.awt.Color(32, 21, 14));
        LastName_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LastName_TextField.setBorder(null);
        LastName_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        LastName_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LastName_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LastName_TextFieldMouseExited(evt);
            }
        });
        LastName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastName_TextFieldActionPerformed(evt);
            }
        });
        DecorationPanel.add(LastName_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 360, 20));

        Day_TextFied.setBackground(new java.awt.Color(255, 255, 255));
        Day_TextFied.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Day_TextFied.setForeground(new java.awt.Color(32, 21, 14));
        Day_TextFied.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Day_TextFied.setBorder(null);
        Day_TextFied.setCaretColor(new java.awt.Color(44, 168, 109));
        Day_TextFied.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Day_TextFiedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Day_TextFiedMouseExited(evt);
            }
        });
        Day_TextFied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Day_TextFiedActionPerformed(evt);
            }
        });
        DecorationPanel.add(Day_TextFied, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 70, 20));

        Password_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Password_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Password_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Password_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Password_TextField.setBorder(null);
        Password_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Password_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Password_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Password_TextFieldMouseExited(evt);
            }
        });
        Password_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_TextFieldActionPerformed(evt);
            }
        });
        DecorationPanel.add(Password_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 360, 20));

        NewUser_Label.setBackground(new java.awt.Color(153, 153, 153));
        NewUser_Label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        NewUser_Label.setForeground(new java.awt.Color(255, 255, 255));
        NewUser_Label.setText("yyyy       -      mm        -     dd");
        DecorationPanel.add(NewUser_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 250, 30));

        RegisterButton_Panel.setBackground(new java.awt.Color(92, 79, 46));
        RegisterButton_Panel.setToolTipText("");
        RegisterButton_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Register_Button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Register_Button.setForeground(new java.awt.Color(255, 255, 255));
        Register_Button.setText("Register Now!");
        Register_Button.setBorderPainted(false);
        Register_Button.setContentAreaFilled(false);
        Register_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Register_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Register_ButtonMouseExited(evt);
            }
        });
        Register_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_ButtonActionPerformed(evt);
            }
        });
        RegisterButton_Panel.add(Register_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 150));

        DecorationPanel.add(RegisterButton_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 160, 150));

        Identification_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Identification_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Identification_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Identification_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Identification_TextField.setBorder(null);
        Identification_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Identification_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Identification_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Identification_TextFieldMouseExited(evt);
            }
        });
        Identification_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Identification_TextFieldActionPerformed(evt);
            }
        });
        DecorationPanel.add(Identification_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 360, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add a Photo");
        DecorationPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 110, 30));

        Email_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Email_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Email_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Email_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Email_TextField.setBorder(null);
        Email_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Email_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Email_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Email_TextFieldMouseExited(evt);
            }
        });
        Email_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_TextFieldActionPerformed(evt);
            }
        });
        DecorationPanel.add(Email_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 360, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender:");
        DecorationPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 80, -1));

        FirstName_TextField.setBackground(new java.awt.Color(255, 255, 255));
        FirstName_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        FirstName_TextField.setForeground(new java.awt.Color(32, 21, 14));
        FirstName_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FirstName_TextField.setBorder(null);
        FirstName_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        FirstName_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FirstName_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FirstName_TextFieldMouseExited(evt);
            }
        });
        FirstName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstName_TextFieldActionPerformed(evt);
            }
        });
        DecorationPanel.add(FirstName_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 360, 20));

        Gender_combobox.setBackground(new java.awt.Color(255, 255, 255));
        Gender_combobox.setForeground(new java.awt.Color(32, 21, 14));
        Gender_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        Gender_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gender_comboboxActionPerformed(evt);
            }
        });
        DecorationPanel.add(Gender_combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 260, -1));

        Photo_Button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Photo_Button.setForeground(new java.awt.Color(153, 153, 153));
        Photo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/camara64.png"))); // NOI18N
        Photo_Button.setBorderPainted(false);
        Photo_Button.setContentAreaFilled(false);
        Photo_Button.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Photo_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Photo_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Photo_ButtonMouseExited(evt);
            }
        });
        Photo_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Photo_ButtonActionPerformed(evt);
            }
        });
        DecorationPanel.add(Photo_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 70, 60));

        Password_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Password_Label.setForeground(new java.awt.Color(255, 255, 255));
        Password_Label.setText("Username:");
        DecorationPanel.add(Password_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 120, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Birth Day:");
        DecorationPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 90, 30));

        Identification_Label.setBackground(new java.awt.Color(255, 255, 255));
        Identification_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Identification_Label.setForeground(new java.awt.Color(255, 255, 255));
        Identification_Label.setText("Identification:");
        DecorationPanel.add(Identification_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        First_Name_Label1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        First_Name_Label1.setForeground(new java.awt.Color(255, 255, 255));
        First_Name_Label1.setText("First Name:");
        DecorationPanel.add(First_Name_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 30));

        Last_Name_Label1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Last_Name_Label1.setForeground(new java.awt.Color(255, 255, 255));
        Last_Name_Label1.setText("Last Name:");
        DecorationPanel.add(Last_Name_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 30));

        Email_Label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Email_Label.setForeground(new java.awt.Color(255, 255, 255));
        Email_Label.setText("Email:");
        DecorationPanel.add(Email_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 30));

        Password_Label1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Password_Label1.setForeground(new java.awt.Color(255, 255, 255));
        Password_Label1.setText("Password:");
        DecorationPanel.add(Password_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, 30));

        Username_TextField1.setBackground(new java.awt.Color(255, 255, 255));
        Username_TextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Username_TextField1.setForeground(new java.awt.Color(32, 21, 14));
        Username_TextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Username_TextField1.setBorder(null);
        Username_TextField1.setCaretColor(new java.awt.Color(44, 168, 109));
        Username_TextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Username_TextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Username_TextField1MouseExited(evt);
            }
        });
        Username_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_TextField1ActionPerformed(evt);
            }
        });
        DecorationPanel.add(Username_TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 360, 20));

        Year_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Year_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Year_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Year_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Year_TextField.setBorder(null);
        Year_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Year_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Year_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Year_TextFieldMouseExited(evt);
            }
        });
        Year_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Year_TextFieldActionPerformed(evt);
            }
        });
        DecorationPanel.add(Year_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 70, 20));

        Month_TextField.setBackground(new java.awt.Color(255, 255, 255));
        Month_TextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Month_TextField.setForeground(new java.awt.Color(32, 21, 14));
        Month_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Month_TextField.setBorder(null);
        Month_TextField.setCaretColor(new java.awt.Color(44, 168, 109));
        Month_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Month_TextFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Month_TextFieldMouseExited(evt);
            }
        });
        Month_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Month_TextFieldActionPerformed(evt);
            }
        });
        DecorationPanel.add(Month_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 70, 20));

        jPanel1.add(DecorationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 630, 480));

        NewUser_Label1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        NewUser_Label1.setForeground(new java.awt.Color(255, 255, 255));
        NewUser_Label1.setText("New User ");
        jPanel1.add(NewUser_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Day_TextFiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Day_TextFiedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Day_TextFiedActionPerformed

    private void Register_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_ButtonActionPerformed
        User_Main_Menu result = new User_Main_Menu();
        result.setVisible(true);
        this.setVisible(false);
        
        int new_person_identification;
        String new_person_first_name;
        String new_person_last_name;
        String new_person_email;
        String new_person_password;
        String new_person_username;
        String new_person_birthay_year;
        String new_person_birthday_month;
        String new_person_birthday_day;

            
        new_person_identification = Integer.parseInt(Identification_TextField.getText());
        new_person_first_name = FirstName_TextField.getText();
        new_person_last_name = LastName_TextField.getText();
        new_person_email = Email_TextField.getText();
        new_person_password = Password_TextField.getText();
        new_person_username = Username_TextField1.getText();
        new_person_birthay_year = Year_TextField.getText();
        new_person_birthday_month = Month_TextField.getText();
        new_person_birthday_day = Day_TextFied.getText();

        int new_person_gender = Gender_combobox.getSelectedIndex();
        
        new_person_birthay_year = Year_TextField.getText();
        new_person_birthday_month = Month_TextField.getText();
        new_person_birthday_day = Day_TextFied.getText();
        
        String new_person_birthday = new_person_birthday_day +"/"+new_person_birthday_month+"/"+new_person_birthay_year;
        System.out.println(new_person_birthday);
        try {
            ConnectDB.insertUser(new_person_identification, new_person_first_name, new_person_last_name, new_person_birthday, new_person_email,new_person_password,new_person_username,new_person_gender,0, 1,1);
        } catch (SQLException ex) {
            Logger.getLogger(Register_Window.class.getName()).log(Level.SEVERE, null, ex);
        }

      
        
    }//GEN-LAST:event_Register_ButtonActionPerformed

    private void Day_TextFiedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Day_TextFiedMouseEntered
        Day_TextFied.setBackground(new java.awt.Color(216,216,216));
    }//GEN-LAST:event_Day_TextFiedMouseEntered

    private void Day_TextFiedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Day_TextFiedMouseExited
        Day_TextFied.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Day_TextFiedMouseExited

    private void Password_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_TextFieldMouseEntered
        Password_TextField.setBackground(new java.awt.Color(216,216,216));
    }//GEN-LAST:event_Password_TextFieldMouseEntered

    private void Password_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Password_TextFieldMouseExited
         Password_TextField.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Password_TextFieldMouseExited

    private void Password_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_TextFieldActionPerformed

    private void Register_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_ButtonMouseEntered
        RegisterButton_Panel.setBackground(new java.awt.Color(68,58,34));
    }//GEN-LAST:event_Register_ButtonMouseEntered

    private void Register_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_ButtonMouseExited
        RegisterButton_Panel.setBackground(new java.awt.Color(92,79,46));
    }//GEN-LAST:event_Register_ButtonMouseExited

    private void LastName_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastName_TextFieldMouseEntered
        LastName_TextField.setBackground(new java.awt.Color(216,216,216));
    }//GEN-LAST:event_LastName_TextFieldMouseEntered

    private void LastName_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastName_TextFieldMouseExited
        LastName_TextField.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_LastName_TextFieldMouseExited

    private void LastName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastName_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastName_TextFieldActionPerformed

    private void Identification_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Identification_TextFieldMouseEntered
        Identification_TextField.setBackground(new java.awt.Color(216,216,216));
    }//GEN-LAST:event_Identification_TextFieldMouseEntered

    private void Identification_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Identification_TextFieldMouseExited
        Identification_TextField.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Identification_TextFieldMouseExited

    private void Identification_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Identification_TextFieldActionPerformed

    }//GEN-LAST:event_Identification_TextFieldActionPerformed

    private void Email_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Email_TextFieldMouseEntered
       Email_TextField.setBackground(new java.awt.Color(216,216,216));
    }//GEN-LAST:event_Email_TextFieldMouseEntered

    private void Email_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Email_TextFieldMouseExited
        Email_TextField.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Email_TextFieldMouseExited

    private void Email_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_TextFieldActionPerformed

    private void FirstName_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstName_TextFieldMouseEntered
        FirstName_TextField.setBackground(new java.awt.Color(216,216,216));
    }//GEN-LAST:event_FirstName_TextFieldMouseEntered

    private void FirstName_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstName_TextFieldMouseExited
        FirstName_TextField.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_FirstName_TextFieldMouseExited

    private void FirstName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstName_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstName_TextFieldActionPerformed

    private void Gender_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gender_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gender_comboboxActionPerformed

    private void Photo_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Photo_ButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Photo_ButtonMouseEntered

    private void Photo_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Photo_ButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Photo_ButtonMouseExited

    private void Photo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Photo_ButtonActionPerformed
         
    }//GEN-LAST:event_Photo_ButtonActionPerformed

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void Username_TextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username_TextField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_TextField1MouseEntered

    private void Username_TextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username_TextField1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_TextField1MouseExited

    private void Username_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_TextField1ActionPerformed

    private void Year_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Year_TextFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_TextFieldMouseEntered

    private void Year_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Year_TextFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_TextFieldMouseExited

    private void Year_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Year_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Year_TextFieldActionPerformed

    private void Month_TextFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Month_TextFieldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Month_TextFieldMouseEntered

    private void Month_TextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Month_TextFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Month_TextFieldMouseExited

    private void Month_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Month_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Month_TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clock;
    private javax.swing.JTextField Day_TextFied;
    private javax.swing.JPanel DecorationPanel;
    private javax.swing.JLabel Email_Label;
    private javax.swing.JTextField Email_TextField;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JTextField FirstName_TextField;
    private javax.swing.JLabel First_Name_Label1;
    private javax.swing.JComboBox<String> Gender_combobox;
    private javax.swing.JLabel Identification_Label;
    private javax.swing.JTextField Identification_TextField;
    private javax.swing.JTextField LastName_TextField;
    private javax.swing.JLabel Last_Name_Label1;
    private javax.swing.JTextField Month_TextField;
    private javax.swing.JLabel NewUser_Label;
    private javax.swing.JLabel NewUser_Label1;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JLabel Password_Label1;
    private javax.swing.JTextField Password_TextField;
    private javax.swing.JButton Photo_Button;
    private javax.swing.JPanel RegisterButton_Panel;
    private javax.swing.JButton Register_Button;
    private javax.swing.JTextField Username_TextField1;
    private javax.swing.JTextField Year_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
